[[
redirects
]]
  from = "/*"
  to = "/index.html"
  status = 200

[
build
]
  command = "npm run build" 
  publish = "build"
[[
headers
]]
  for = "/*"
    [
headers.values
]
    Cache-Control = "public, max-age=0, must-revalidate"